name: heyava_authentication
description: An awesome Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0  

  cupertino_icons: ^1.0.2
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  flutter_mobx: ^2.0.6+5
  build_runner: ^2.4.6
  get_it: ^7.6.0
  dio: ^5.2.1+1
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  sqflite_common_ffi: 2.2.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ava_logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/

